### ISSUE TITLE
Palestine flag 🇵🇸 does not render

### ISSUE THREAD

**Issue by xurizaemon** [sethfischer/mundo-flags#1]
Just flagging (haha) this for your attention 😁 

https://github.com/sethfischer/mundo-flags/blob/e205ac06a893ffcfda31121d2ef8186c03f3e4fa/svg/ps.svg

![image](https://user-images.githubusercontent.com/105608/132149306-c3b627aa-16ff-451c-ae8e-78f7d59d8167.png)

**Comment by sethfischer** [comment]
Thanks @xurizaemon, this bug affects all placeholder images (AQ, EH, PS, and SJ).
